defaults: base.yaml

run_name: "M4_fml_pretrain_cifr"

data:
  target: eightclass_yaml_path
  eightclass_yaml_path: "data/eightclass/datasets/RFT.yaml"



model:
  use_cifr: true
  cifr_weighting: "inv_sqrt_freq"
  pretrained_backbone: "./checkpoints/phase2_fml_pretrained_backbone.pt"

train:
  finetune_strategy: "gradual_unfreeze"
  unfreeze_schedule: [15, 30, 45]
  device: 0

wandb:
  tags: ["main-result", "phase4", "fml-pretrain", "cifr"]
