defaults: base.yaml
run_name: "Phase2_FML_Pretrain"
data:
  target: fml_yaml
model:
  use_cifr: false
  base: "yolov8m"
  img_size: 480
train:
  epochs: 150
  finetune_strategy: "full_finetune"
  device: 0
  cache: true
wandb:
  tags: ["phase2", "fml-pretrain", "single-class"]
